# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trans_image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11trans_image.proto\x12\x0btrans_image\"\x1b\n\nDataRquest\x12\r\n\x05image\x18\x01 \x01(\t\"-\n\x0c\x44\x61taResponse\x12\r\n\x05image\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65tect\x18\x02 \x01(\t2K\n\nTransImage\x12=\n\x05trans\x12\x17.trans_image.DataRquest\x1a\x19.trans_image.DataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trans_image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATARQUEST._serialized_start=34
  _DATARQUEST._serialized_end=61
  _DATARESPONSE._serialized_start=63
  _DATARESPONSE._serialized_end=108
  _TRANSIMAGE._serialized_start=110
  _TRANSIMAGE._serialized_end=185
# @@protoc_insertion_point(module_scope)
